# Module 2: Configuring Model Parameters {#C03_1 -}

### Getting Familiar with the .nml {#C03_2 -}

To configure the model, open the `glm3.nml` file in the *Kinneret97* directory with a text editor. A chunk of this `.nml` file is shown below. For example, if you wanted to change the maximum number of lake layers the model simulates, you would change `max_layers = 500`.

```{block2, hint03_4, type='rmdnote2'}
The easiest way to edit the `glm3.nml` file is with the Atom text editor. You can download it [here](https://atom.io).
```

```{style="max-height: 400px;"}
!------------------------------------------------------------------------------!
!                                                                              !
!          .----------------.  .----------------.  .----------------.          !
!          | .--------------. || .--------------. || .--------------. |        !
!          | |    ______    | || |   _____      | || | ____    ____ | |        !
!          | |  .' ___  |   | || |  |_   _|     | || ||_   \  /   _|| |        !
!          | | / .'   \_|   | || |    | |       | || |  |   \/   |  | |        !
!          | | | |    ____  | || |    | |   _   | || |  | |\  /| |  | |        !
!          | | \ `.___]  _| | || |   _| |__/ |  | || | _| |_\/_| |_ | |        !
!          | |  `._____.'   | || |  |________|  | || ||_____||_____|| |        !
!          | |              | || |              | || |              | |        !
!          | '--------------' || '--------------' || '--------------' |        !
!          '----------------'  '----------------'  '----------------'          !
!                                                                              !
!-------------------------------------------------------------------------------

!-------------------------------------------------------------------------------
! general model setup
!-------------------------------------------------------------------------------
&glm_setup
   sim_name = 'Example Kinneret GLM Simulation'
   max_layers = 500
   min_layer_vol = 0.025
   min_layer_thick = 0.15
   max_layer_thick = 1.50
   density_model = 1
/
```

### Exercise: Adding Output Points {#C03_3 -}

1) Go to the `&output` section of `glm3.nml` and customize the configuration to make two output files, one at 5m from the bottom (ie. in the lake hypolimnion) and one at 35m from the bottom (ie. in the lake epilimnion). This create two `.csv` files (`WQ_5.csv` and `WQ_35.csv`) with conditions at these water depths. Plot the temperate of the two layers in excel. Identify the periods where the lake is stratified and mixed.

```{style="max-height: 239px;"}
!-------------------------------------------------------------------------------
! format for output and filename(s)
!-------------------------------------------------------------------------------
&output
   out_dir = 'output'
   out_fn  = 'output'
   nsave = 6  !This will output every 6 hours
   ! General summary file
   csv_lake_fname = 'lake'
   ! Depth specific outputs
   csv_point_nlevs = 2 
   csv_point_fname = 'WQ_'
   csv_point_at = 5.,35.
   csv_point_nvars = 4
   csv_point_vars = 'temp','salt','PHS_frp','NIT_amm'
/
```

2) Assess how the degree of stratification changes as the initial water level of the lake is reduced by 20m. To do this change the initial starting lake depth and profile details in `glm3.nml`.

```{block2, hint09_7, type='rmdtip2'}
You will need to update the output depth of your surface output file.
```

```{block2, hint09_8, type='rmdtip2'}
For future activities make sure you change back to 43m.
```

