# Error Assessment {#error-assessment -}

## Mean Absolute Error (MAE) {#C05_2 -}

Mean absolute error measures the average absolute difference between the simulated results and the observed results. It is calculated by summing the absolute error between paired values (i.e. modeled and actual) and dividing by the number of observations:

<center>
\begin{equation}
MAE = \frac{\sum_{i}\left | T_{i}^{sim}-T_{i}^{obs} \right |}{n}
(\#eq:05-1)
\end{equation}
</center>

## Sensitivity Index (SI) {#C05_3 -}

Calculating a sensitivity index allows the impact of changing an independent variable to be assessed on a dependent variable. Given all other variables are held constant, the SI is computed by dividing the percentage change in the simulated result (i.e. the output) by the percentage change of the input parameter:

<center>
\begin{equation}
SI = \frac{(Output_{new}-Output_{original})/Output_{original}}{(Parameter_{new}-Parameter_{original})/Parameter_{original}}
(\#eq:05-2)
\end{equation}
</center>
