# Getting Started {#GettingStarted .unnumbered}

## Tools You'll Need {.unnumbered}

### Text Editor {.unnumbered}

A text editor is required to edit GLM's `.nml` configuration files. Simple text editors like *TextEdit* on MacOS or *Wordpad* on Windows can be used however more extensible editors like [Visual Studio Code](https://code.visualstudio.com), UltraEdit or [Atom](https://atom.io) are recommended. 

To edit the `.nml` file, simply right click on the file and open it in your preferred text editor. Changes to the file must be saved before running GLM. Any text with a '!' before it is not read by the program, but is used as a comment for the user. 

### Excel {.unnumbered}

GLM reads and writes data in CSV format. Excel can be used to edit these files (e.g. time series meteorological input data) or for plotting outputs.

### R {.unnumbered}

R is also commonly used to manipulate and visualise GLM's input/output data.

-   R can be downloaded [here](https://cran.csiro.au)
-   R Studio can be downloaded [here](https://rstudio.com)


## Case-study download {.unnumbered}

The GLM model and two case-study simulations setup for the below exercises are available for download by clicking the download button in the tool bar <i class="fa fa-download" aria-hidden="true"></i>.

The simulation in the WarmLake directory is an example 40 m deep, monomictic lake that is used to supply drinking water and support an active fishery. 

The simulation in the TropicalReservoir directory is a typical water supply reservoir (drowned river valley) located in a sub-tropical climate. This simulation is polymictic, mixing variably throughout the year.

Other model simulations are also available in the glm-aed GitHub repository in glm-examples directory.

## Unzipping files {.unnumbered}

The GLM model and case study simulations featured in this workbook are distributed as a zipped file. In some cases users may erroneously be working "within" the zip without properly extracting the file and this prevents the simulation from running.

Extracting these files will depend on your operating system.

On MacOS, simply double click the 'zipped' file:

<center>

<video width="100%" height="100%" controls>
<source src="images/01-gettingstarted/video1.mp4" type="video/mp4">
</video>

</center>

<br>

On Windows, click 'Extract All' and follow the prompt:

<center>
<video width="100%" height="100%" controls>
<source src="images/01-gettingstarted/video2.mp4" type="video/mp4">
</video>

</center>

<br>
